name: Semantic Release

on: [check_suite, check_suite:completed]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: relase
        # if: github.event.check_suite.status == 'completed' && github.event.check_suite.conclusion == 'success' && ${GITHUB_REF} == 'saga'
        env:
          GK_LOCK_DEFAULT_BRANCH: saga
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          sudo npm install -g npm@
          npm ci --no-audit
          npx tsc
          npm i --no-save semantic-release@next
          npx semantic-release
